### ISSUE TITLE
Incorrect cooked traces?

### ISSUE THREAD

**Issue by Apolotary** [hongzimao/pensieve#1]
Hi, 

I'm trying to run the sim/multi_agent.py script, but there seems to be an issue. I downloaded your cooked_traces folder from dropbox and put it into the sim folder as the readme file requested. The problem is, the cooked_traces file contain only one column, whereas it looks like your script load_traces.py requires two columns instead.

Am I calling the wrong script or should there be different data instead? Also, how do I "cook" traces myself?

Thanks!

**Comment by hongzimao** [comment]
For `sim/multi_agent.py`, we need to use `train_sim_traces` and `test_sim_traces` instead of `cooked_traces`. The one column `cooked_traces` is for actual experiments, which is in mahimahi format (details: https://github.com/ravinet/mahimahi). Hope this helps.

**Comment by Apolotary** [comment]
That fixed it, thanks!!
