### ISSUE TITLE
A few questions when run multi_agent.py with cpu and gpu?

### ISSUE THREAD

**Issue by lmnbsyq** [hongzimao/pensieve#12]
Hi:
        I tested with Ubuntu 14.04, Tensorflow v1.4.0, TFLearn v0.3.2 and Selenium v2.39.0,The data is your sample training/testing data(train_sim_traces and test_sim_traces).
        I  installed pensieve and run testing environmet: python rl_no_training.py , it's ok whatever run at cpu or gpu.
        
        But there are some questions when I'm running training: python multi_agent.py
        Run at GPU error info:
                1. keep_dims is deprecated, use keepdims instead
                    WARNING:tensorflow:Error encountered when serializing data_augmentation.
                            Type is unsupported, or the types of the items don't match field type in CollectionDef.
                             'NoneType' object has no attribute 'name'
                2.  W tensorflow/core/grappler/utils.cc:48] Node actor/FullyConnected/MatMul_fused is not in the graph.
                      Process Process-1:
                      Traceback (most recent call last):
                      File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
                      self.run()
                     File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
                        self._target(*self._args, **self._kwargs)
                     File "multi_agent.py", line 143, in central_agent
                       s_batch=np.stack(s_batch, axis=0),
                    File "/usr/local/lib/python2.7/dist-packages/numpy/core/shape_base.py", line 350, in stack
                     raise ValueError('need at least one array to stack')
                     ValueError: need at least one array to stack
        Run at CPU error info:
               1.Instructions for updating:
                  Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent behavior.
                WARNING:tensorflow:Error encountered when serializing data_augmentation.
                 Type is unsupported, or the types of the items don't match field type in CollectionDef.
                 'NoneType' object has no attribute 'name'

      　Am I calling the wrong script or should be fix the environment? What do I need to do to fix it next?
　　　Hope to get your reply , thanks!

**Comment by hongzimao** [comment]
Af a first glance, it looks like the environment is not set up correctly. Just for reproducing the results, we recommend using the same environment we used for developing Pensieve, i.e., `Ubuntu 16.04, Tensorflow v1.1.0, TFLearn v0.3.1 and Selenium v2.39.0`. Tensorflow is updated very rapidly (and wildly) and might result in unwanted artifacts.

**Comment by lmnbsyq** [comment]
@hongzimao 
　　Thanks for your reply . 
　　I set environment as :Ubuntu 16.04, Tensorflow v1.1.0, TFLearn v0.3.1 and Selenium v2.39.0. But it has not been solved and there are same problem as before,

　　python muti_agent.py error info:
　　　　WARNING:tensorflow:Error encountered when serializing data_augmentation.
　　　　Type is unsupported, or the types of the items don't match field type in CollectionDef.
　　　　'NoneType' object has no attribute 'name'
　　　　WARNING:tensorflow:Error encountered when serializing data_preprocessing.
　　　　Type is unsupported, or the types of the items don't match field type in CollectionDef.
　　　　'NoneType' object has no attribute 'name'
　　　　Process Process-1:
　　　　Traceback (most recent call last):
　　　　File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
　　　　　　self.run()
　　　　File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
　　　　　　self._target(*self._args, **self._kwargs)
　　　　File "multi_agent.py", line 143, in central_agent
　　　　　　s_batch=np.stack(s_batch, axis=0),
　　　　File "/usr/local/lib/python2.7/dist-packages/numpy/core/shape_base.py", line 350, in stack
　　　　　　raise ValueError('need at least one array to stack')
　　　　　　ValueError: need at least one array to stack

　　I think these questions are not related to  environment, because I can run test/rl_no_training.py , and it's ok 。
　　rl_no_training.py log info:
　　　　2017-11-17 16:49:19.012283: W tensorflow/core/platform/cpu_feature_guard.cc:45] The    TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine   and could speed up CPU computations.
　　　　Model restored.
　　　　video count 0
　　　　video count 1
　　　　....
　　　　video count 126

　　Is it caused by other problems? how should I solve it?

**Comment by hongzimao** [comment]
`ValueError: need at least one array to stack` suggests in `s_batch=np.stack(s_batch, axis=0)` `s_batch` is empty. I think the data loading might have some problem, which results in this sudden termination in the training episode.

**Comment by lmnbsyq** [comment]
I used your test data (train_sim_traces and test_sim_traces) , what shoud I do if the data loading have problem?

**Comment by hongzimao** [comment]
I think you might need to put traces in the right folder. As said in `sim/README.md`---put training data in `sim/cooked_traces` and testing data in `sim/cooked_test_traces` (need to create folders).

**Comment by lmnbsyq** [comment]
I had been put training data in sim/cooked_traces and testing data in sim/cooked_test_traces,and follow and operate README.md's requirements  all the time.
Is it error "WARNING:tensorflow:Error encountered when serializing data_augmentation.Type is unsupported, or the types of the items don't match field type in CollectionDef.'NoneType' object has no attribute 'name'" cause this problem?

**Comment by hongzimao** [comment]
I think that was just a `WARNING`. The error message is `ValueError: need at least one array to stack`, which suggests `s_batch` in `s_batch=np.stack(s_batch, axis=0)` is empty.

**Comment by lmnbsyq** [comment]
Get test data:
I downloaded test_sim_traces and train_sim_traces data from https://www.dropbox.com/sh/ss0zs1lc4cklu3u/AAB-8WC3cHD4PTtYT0E4M19Ja?dl=0, put training data in sim/cooked_traces and testing data in sim/cooked_test_traces, 
     cp test_sim_traces/* sim/cooked_test_traces/
     cp train_sim_traces/* sim/cooked_traces

what should I  try to do to solve this problem？

**Comment by hongzimao** [comment]
Did you do `python get_video_sizes` as in `sim/README.md`?

**Comment by lmnbsyq** [comment]
yes
my installing and running steps:
git clone https://github.com/hongzimao/pensieve
python setup.py (success ,and I try to install use shell from setup.py . All is ok and enviroment is Ubuntu 16.04, Tensorflow v1.1.0, TFLearn v0.3.1 and Selenium v2.39.0)
download data (cp test_sim_traces/* sim/cooked_test_traces/ ; cp train_sim_traces/* sim/cooked_traces)
cd sim 
python get_video_sizes.py(success)　video_size_0-6 are produced
  example:-rw-r--r--  1 root  root    343 11月 17 16:28 video_size_0
python multi_agent.py(with above problem )

**Comment by hongzimao** [comment]
Interesting, we never encountered this problem before (and those who reproduced our results didn't report this problem). You said you are able to load the pretrained model and run `rl_no_training.py`; this means tensorflow setup is fine. Debugging this needs a little more understanding of the code. I would start with understanding how `s_batch` (state observations) is created and filled in each worker, and try to dig out why it is empty by the time worker reports it to the master.

**Comment by lmnbsyq** [comment]
Surprisingly, It's working with cpu now when I changed NUM_AGENTS.
But there are still some errors  when it's running at gpu.The error means "out of memory" and "Failed to create session" .  Should I reduce the value of NUM_AGENTS in multi_agent.py order to fix  "out of memory" error? if not , what should I do?

**Comment by lmnbsyq** [comment]
There are train model in result/, and I want to run real_exp/run_exp.py by using local machine to get result , 
I copy sim/result/*   rl_server/results/
rl_server/rl_server_no_training.py set NN_MODEL = '../rl_server/results/nn_model_ep_10200.ckpt'
what should I modify url in run_video.py to the server address(which is local machine)? I think it neednot modify. it is localhost. But chrome_retry_log message is "HTTP Error 503: Service Unavailable". what means  server address url ? could you give me a example?
Thanks for your help.

**Comment by hongzimao** [comment]
So the problem is the GPU memory allocation of your setting. I believe our released version of the code didn't use GPU: https://github.com/hongzimao/pensieve/blob/master/sim/multi_agent.py#L5. 

I would adjust the memory limit for each worker thread, as opposed to limiting the number of workers. The performance may depend on the degree of parallelism. Please refer to Pensieve paper section 4.2 and reference [30] for more details about this point.

**Comment by SuperStoneliu** [comment]
I occur the same problem of GPU "out of memory",I wonder how you solve this problem last. @lmnbsyq @

**Comment by miqianmimi** [comment]
I occur the same problem like

> WARNING:tensorflow:Error encountered when serializing data_preprocessing.
>　　　　Type is unsupported, or the types of the items don't match field type in CollectionDef.
>　　　　'NoneType' object has no attribute 'name'

I wonder whether you have solve this problem. thank you .
