### ISSUE TITLE
Cannot find Gruntfiles.js

### ISSUE THREAD

**Issue by Hgit007** [hongzimao/pensieve#120]
Hi Hongzi,

I would like to modify the dash.js. Then I build dash.js with the commond  `grunt --config Grunfile.js --force` or  `grunt --config ./Grunfile.js --force`. I don't know why _Task "Gruntfile.js" not found_. Is there something I am missing? Thanks in advance.

![image](https://user-images.githubusercontent.com/39703828/96399795-3617d000-119d-11eb-991e-f2c311d39339.png)

Best,

**Comment by ry4nzhu** [comment]
I am having the same problem. How do you resolve that?

**Comment by talha-waheed** [comment]
I am also facing the same error. @Hgit007 were you able to resolve it?

**Comment by hongzimao** [comment]
This might be helpful: #10
