### ISSUE TITLE
Potential bug: test/mpc.py ValueError: too many values to unpack

### ISSUE THREAD

**Issue by ry4nzhu** [hongzimao/pensieve#123]
I am trying to get familiar with the codebase and run through some experiments. In test folder, when I tried to run `python mpc.py` after getvideosize, I got `  File "mpc.py", line 91, in main
    net_env.get_video_chunk(bit_rate)
ValueError: too many values to unpack`. It is because that at `test/fixed_env.py:48`, the function returns 8 values when in `mpc.py:91` it only uses 7 values to receive them.

**Comment by hongzimao** [comment]
Good findings! Can you try using the arguments in `rl_no_training.py` for the problematic part in `mpc.py`? Would be helpful for others if you can post your solutions as well. Thanks!

**Comment by ry4nzhu** [comment]
Exactly, the arguments in `rl_no_training.py` has the correct number. My solution is to create a dummy variable `        next_video_chunk_sizes = []
delay, sleep_time, buffer_size, rebuf, \
        video_chunk_size, \
        next_video_chunk_sizes, \
        end_of_video, video_chunk_remain = \
            net_env.get_video_chunk(bit_rate)` around line 91 in `test/mpc.py`.
