### ISSUE TITLE
data source selection

### ISSUE THREAD

**Issue by pengyuan-zhou** [hongzimao/pensieve#127]
Hi Hongzi,

Thanks for the great work.

Just wondering, is there a specific reason for choosing FCC data from the "Web Browsing" category, instead of the "Video Streaming" category?

Thanks.
BR.
Pengyuan

**Comment by hongzimao** [comment]
Good observation. It's because prior work was using this category and we wanted to do an apple-to-apple comparison.

**Comment by pengyuan-zhou** [comment]
I see. 
Thanks for the reply :)
