### ISSUE TITLE
Out of bounds error while implementing dp.cc

### ISSUE THREAD

**Issue by naman-32** [hongzimao/pensieve#132]
Hi,

First of all great work! I really enjoyed the paper.
And thanks for providing the implementation details publicly!

I am trying to reuse your [dp.cc](https://github.com/hongzimao/pensieve/blob/master/test/dp.cc) implementation in a slightly different context in project where format of video metadata file is different. So, I have tweaked [dp.cc](https://github.com/hongzimao/pensieve/blob/master/test/dp.cc) a bit to parse video metadata and hence populate the data pretty much in the same way as in original implementation. 

The script successfully performs offline optimal simulation correctly on most of the cases, but for certain combination of video and trace file , I got a segmentation error at [					`download_time = all_download_time[n][t][nm];`](					https://github.com/hongzimao/pensieve/blob/1120bb173958dc9bc9f2ebff1a8fe688b6f4e93c/test/dp.cc#L417). `t` is this case was detected to be [`t_max_idx`](https://github.com/hongzimao/pensieve/blob/1120bb173958dc9bc9f2ebff1a8fe688b6f4e93c/test/dp.cc#L326) +1 (or 2). I would be grateful if you could please spare some time to indicate towards possible sources of this error. Please comment if some other details are required from my end.    

P.S. :-  The error was temporarily resolved by setting [`_t_portion_`](https://github.com/hongzimao/pensieve/blob/1120bb173958dc9bc9f2ebff1a8fe688b6f4e93c/test/dp.cc#L321) to be 1. And, I have matched all data units to the original script.

Thanks in advance,
[Naman](https://github.com/naman-32)

**Comment by hongzimao** [comment]
I think the segmentation fault means `t` overflows the total simulation duration. There might be some hardcoded horizon for the dp (we were manually setting it as the max across all traces we dealt with). When using a new trace, you may need to update those max (or truncating your trace files).

I think `_t_portion_` have to do with when a video chunk is downloaded within a 2 or 4 seconds interval. Setting it to 1 may make the simulation jump in the trace file (e.g., some portion of the interval isn't used by the corresponding bandwidth). 

Hope these help.

**Comment by joybi531** [comment]
@naman-32 
Hi,
I was trying to do this experiment but unfortunately, I am not being able to get access to any of the raw data (zip file) and cooked_trace data. Do you have any of these two or both of them? I would really appreciate any support or information on where I can find the dataset.

Note: I have checked on the fcc.gov website but couldn't download the data due to some error.

**Comment by naman-32** [comment]
Hi, 

The cooked_trace data samples doesn't seem to be accessible now on [link provided](https://www.dropbox.com/sh/ss0zs1lc4cklu3u/AAB-8WC3cHD4PTtYT0E4M19Ja?dl=0) in the repository. I was working on different private cooked_trace dataset, which I cannot share due to NDA.

Best
Naman
