### ISSUE TITLE
how  to run the script on  the gpu?

### ISSUE THREAD

**Issue by boshanyiqiao** [hongzimao/pensieve#14]
Hi:
   There are four gpu card in machine.I wanted to run the script on the gpu , then modified os.environ['CUDA_VISIBLE_DEVICES']='0' in sim/multi_agent.py and rl_server/rl_server_no_training.py.But the sim/multi_agent.py and run_exp/run_all_traces.py still ran at cpu,did I modified scripts are wrong? how should I do?
Thanks for your help.

**Comment by hongzimao** [comment]
Did you install the GPU version tensorflow? Also, the benefit of using GPU might not be that dramatic given the size of the (original) problem.

**Comment by lmnbsyq** [comment]
yes , i had been installed tensorflow-gpu。
I modified os.environ['CUDA_VISIBLE_DEVICES']='' to os.environ['CUDA_VISIBLE_DEVICES']='0' ,order to run the script on the gpu which one is I specified and its number is 0 on the machine.
I tried it again, but still ran on cpu .
I want to get performance on gpu ,

**Comment by hongzimao** [comment]
Hmm, https://github.com/hongzimao/pensieve/blob/master/sim/multi_agent.py#L88 and https://github.com/hongzimao/pensieve/blob/master/sim/multi_agent.py#L208 just create tensorflow default session; it should use GPU if your machine supports it. Try removing `os.environ['CUDA_VISIBLE_DEVICES']=''`, this should really fall back to the default setting.

Also, try a dummy tensorflow computation right after importing the library; would that be using GPU? If not, it means the imported library disables the GPU(s) already.

**Comment by boshanyiqiao** [comment]
Aha! it's ok , thanks a lot
