### ISSUE TITLE
 k = 8 past bandwidth and Next chunk sizes

### ISSUE THREAD

**Issue by ali1hammoud** [hongzimao/pensieve#143]
I read and quote:

> 4.4 Implementation
> To generate ABR algorithms, Pensieve passes k = 8 past bandwidth
> measurements to a 1D convolution layer (CNN) with 128 filters,
> each of size 4 with stride 1. Next chunk sizes are passed to another
> 1D-CNN with the same shape

How did you choose k to be 8? why isn't another value? how do we determine this value or according to what?
can you mention it in the code "k = 8 past bandwidth and Next chunk sizes" ?? 
Thank you.

**Comment by hongzimao** [comment]
Good question. In development, we tested a few values - for k < 8 there might be a performance degradation, for k >=8 the performance doesn't change much - in essence, we just used the minimum number past observations that worked. Hope this helps.

**Comment by ali1hammoud** [comment]
Yes, thank you. That was helpful.
