### ISSUE TITLE
How did you control the entropy factor $\beta$ from 1 to 0.1?

### ISSUE THREAD

**Issue by yixin94** [hongzimao/pensieve#16]
Hi Hongzi,

Does the constant variable `ENTROPY_WEIGHT = 0.5` in a3c.py refer to $\beta$ in equation 4 in Sec. 4.2? (https://github.com/hongzimao/pensieve/blob/1120bb173958dc9bc9f2ebff1a8fe688b6f4e93c/sim/a3c.py#L8)
But it seems no code changes the value of `ENTROPY_WEIGHT` and it remains fixed through the whole training process. How did you make it vary from 1 to 0.1?
Thank you!

**Comment by hongzimao** [comment]
Thanks for pointing this out. Please find our response to a similar question here: https://github.com/hongzimao/pensieve/issues/11.

**Comment by yixin94** [comment]
I got it. Thank you! ^_^
