### ISSUE TITLE
env.py delay noise implementation

### ISSUE THREAD

**Issue by pablogil16** [hongzimao/pensieve#17]
Hi,

Checking env.py I realised you added some noise to the total delay as follows:

     delay *= MILLISECONDS_IN_SECOND
     delay += LINK_RTT
     delay *= np.random.uniform(NOISE_LOW, NOISE_HIGH)

I would like to know why you added noise to the total delay. 

I understand the noise for the propagation delay (LINK_RTT) in order to avoid overfitting to 80ms, as it is constant for the whole training. However, the transmission delay always depends on the link's throughput, which is gathered from the traces and changes for each second. The throughput values are actually real values achieved by apps in the wild and in principle adding noise wouldn't make sense to me.

Thank you so much!

**Comment by hongzimao** [comment]
We just wanted the learning agent to experience more diverse input conditions (for more robust performance). Feel free to drop that term (or increase the noise level) and see if it affects the performance.

**Comment by pablogil16** [comment]
Thanks for your answer! I thought it was because of that, but I wanted to make sure. :-)
