### ISSUE TITLE
Some questions about the environment

### ISSUE THREAD

**Issue by shinshiner** [hongzimao/pensieve#18]
Hi, hongzi. I tried to reproduce your pensieve system. However, I found whatever bitrate the agent choiced, the `rebuf time` was always 0, then the agent would just choice one action for every chunk because it always received positive reward. I really do not understand how this happened. The data was downloaded from your dropbox. Any help would be great appreciated.

**Comment by hongzimao** [comment]
I really don't understand this either. We never (nor did those who reproduced our results) saw this before. Could you be more specific? How did you run the experiment? How did you record the rebuffering time? Try to narrow down the problem to the most specific please. Thanks.

**Comment by shinshiner** [comment]
In common sense, when the buffer size is up to threshold, the environment should rebuffer to get next video chunk, but when the buffer is full, the rebuffer time is still 0, which is really strange.

**Comment by shinshiner** [comment]
I ran your pretrained model again and printed the result of rebuffering time, and I found it would be 0 most of the time, expect of the last few chunks. The rebuffering time here is just the fourth return value `rebuf` of the `get_video_chunk` function.

**Comment by hongzimao** [comment]
So the rebuffering time is not always 0 then. Also, I guess this means the pretrained model is doing a good job, isn't it?

Honestly I'm really confused by what you are saying but somehow I think (I might be wrong) our definitions of "rebuffering" differ. Could you check with our paper Section 2 (especially (2)), or the MPC paper [51] for reference?

**Comment by shinshiner** [comment]
It would be fine to avoid rebuffering when we test the model. However, if the rebuffering time is also 0 in training stage, the agent will always get positive reward and will choice same action as before. Then the agent will finally just choice one action for any videos. That's what confuse me most. Have you met similar problem in your training stage ?

**Comment by shinshiner** [comment]
Refer to the following code, in my training stage, the `rebuffer penalty` will be 0 due to the value of `rebuf` is always 0. Finally, the agent will learn to choice only one action to make `smooth penalty` as 0 because this can maximize its reward.
```
# reward is video quality - rebuffer penalty - smooth penalty
            reward = VIDEO_BIT_RATE[bit_rate] / M_IN_K \
                     - REBUF_PENALTY * rebuf \
                     - SMOOTH_PENALTY * np.abs(VIDEO_BIT_RATE[bit_rate] -
                                               VIDEO_BIT_RATE[last_bit_rate]) / M_IN_K
```

**Comment by hongzimao** [comment]
This looks strange and I think we never saw what you observed during our training. You might want to dig into this a bit and see where it went wrong. Notice that the average bandwidth is roughly in the midway of all available bitrate. Therefore, random policy (before any training) should result in fair amount of rebuffering.

**Comment by shinshiner** [comment]
I found this case will appear when I just use current state to train. If I combine past several states to train, things would be better and can get satisfactory results. Many thanks to your reply !
