### ISSUE TITLE
A few questions about the real experiment of pensieve

### ISSUE THREAD

**Issue by shinshiner** [hongzimao/pensieve#19]
Hi hongzi, I have trained a model and found it performs well in test traces. I tend to apply it into real experiment and implement a presentation effect like that in the beginning [your video](https://www.youtube.com/embed/TJpQXgby_tk), namely two videos are being played and the bitrates are showed in lower right corner. However, I am not fully understand what I should do according to your README.md.
1) According to the REAME.md, I need to setup a server, then the video file should be put in local? Or I can open a specific website to download the video?
2) What are the files like 'myindex_BB.html' used for ? Each of them may just have a empty video player? Or I need this to play the video?

I would appreciate it if you can give some tips or some more detailed steps. Thanks you !

**Comment by hongzimao** [comment]
1. Please follow the `Running experiments over Mahimahi` section in `README.md`. The network is emulated using mahimahi, therefore server and client can both be on your local machine. Alternatively, you can run experiments over the real network. To do that, follow `Real-world experiments` in `README.md`.

2. `myindex_BB.html` is using "buffer-based" ABR algorithm. They actually load a video provided in `video_server`. To massively run the experiment, we load videos in a virtual display (i.e., https://github.com/hongzimao/pensieve/blob/master/setup.py#L25). Details can be found in `README.md`.

**Comment by shinshiner** [comment]
I did follow the README.md step by step, but I get stuck in this instrcution `modify url in run_video.py to the server address`. Maybe the server address points to the apache2 server ? I referred to some tutorials to setup an apache2 server, but they seemed to be not useful. For this project, is there any suitable tutorials to set a server ? By the way, is there any limitations for video format ? Or just a `.mp4` file is OK ?

**Comment by shinshiner** [comment]
I think I am gradually familiar with the environment and can make the video played in the virtual browser. But I still have a question: when I do real world experiments, what limit the transmission speed? If I want to limit the speed according to my settings, I need to restart the apache2 server, which may interrupt the video playing...
