### ISSUE TITLE
A question about the network in a3c.py

### ISSUE THREAD

**Issue by yangchaozhao** [hongzimao/pensieve#20]
Hi, hongzi:
I found line 290 to 291 in `a3c.py` as follows:

`split_4 = tflearn.conv_1d(inputs[:, 4:5, :A_DIM], 128, 4, activation='relu')`
`split_5 = tflearn.fully_connected(inputs[:, 4:5, -1], 128, activation='relu')`

, and I wonder why the `split_5` takes the  `inputs[:, 4:5, -1]` as it's input rather than 
`inputs[:, 5:6, -1]` ? I think `s_batch[:, 4:5, :A_DIM]` stands for the `next_video_chunk_size` vector and `split_5` should take the `video_chunk_remain` as input, which corresponds to `s_batch[:, 5:6, -1]`.
Looking forward to your reply.

**Comment by hongzimao** [comment]
Excellent catch! I think this is a typo when we tidy up our code for public release. Making the correct change as you suggested should improve the performance (as we reported in section 4.2 and presentation slide 18 point 3). Feel free to have a try and you should get a better model (more faithful to the paper). Thanks a lot for your discovery.

**Comment by yangchaozhao** [comment]
Thank you for your reply!
