### ISSUE TITLE
View the results

### ISSUE THREAD

**Issue by AnatoliyZabrovskiy** [hongzimao/pensieve#21]
Hello! Thank you for your software. Unfortunately I cannot get the results. I use Ubuntu 16.04,  Tensorflow 1.1.0,  TFLearn 0.3.1.  Figure does not show any results.

pensieve/test$ python plot_results.py 
log_sim_rl_norway_tram_27
log_sim_rl_norway_metro_5
log_sim_rl_norway_metro_1
log_sim_rl_norway_tram_6
log_sim_rl_norway_tram_51
log_sim_rl_norway_car_8
log_sim_rl_norway_tram_50
log_sim_rl_norway_tram_5
log_sim_rl_norway_tram_28
log_sim_rl_norway_car_3
log_sim_rl_norway_car_1
log_sim_rl_norway_bus_19
log_sim_rl_norway_bus_13
log_sim_rl_norway_ferry_5
log_sim_rl_norway_bus_11
log_sim_rl_norway_train_18
log_sim_rl_norway_bus_14
log_sim_rl_norway_tram_10
log_sim_rl_norway_tram_17
log_sim_rl_norway_bus_17
log_sim_rl_norway_tram_25
log_sim_rl_norway_tram_2
log_sim_rl_norway_train_11
log_sim_rl_norway_train_1
log_sim_rl_norway_ferry_10
log_sim_rl_norway_bus_21
log_sim_rl_norway_bus_8
log_sim_rl_norway_tram_47
log_sim_rl_norway_bus_5
log_sim_rl_norway_ferry_8
log_sim_rl_norway_tram_21
log_sim_rl_norway_tram_55
log_sim_rl_norway_train_8
log_sim_rl_norway_train_21
log_sim_rl_norway_tram_41
log_sim_rl_norway_train_10
log_sim_rl_norway_tram_53
log_sim_rl_norway_train_3
log_sim_rl_norway_ferry_17
log_sim_rl_norway_bus_18
log_sim_rl_norway_tram_48
log_sim_rl_norway_metro_10
log_sim_rl_norway_ferry_7
log_sim_rl_norway_bus_2
log_sim_rl_norway_bus_16
log_sim_rl_norway_car_5
log_sim_rl_norway_ferry_19
log_sim_rl_norway_tram_39
log_sim_rl_norway_tram_29
log_sim_rl_norway_ferry_2
log_sim_rl_norway_tram_33
log_sim_rl_norway_train_14
log_sim_rl_norway_tram_7
log_sim_rl_norway_bus_7
log_sim_rl_norway_ferry_11
log_sim_rl_norway_tram_18
log_sim_rl_norway_ferry_14
log_sim_rl_norway_metro_7
log_sim_rl_norway_ferry_1
log_sim_rl_norway_bus_1
log_sim_rl_norway_ferry_16
log_sim_rl_norway_tram_4
log_sim_rl_norway_metro_9
log_sim_rl_norway_tram_43
log_sim_rl_norway_tram_14
log_sim_rl_norway_train_2
log_sim_rl_norway_bus_4
log_sim_rl_norway_ferry_18
log_sim_rl_norway_train_7
log_sim_rl_norway_bus_20
log_sim_rl_norway_car_12
log_sim_rl_norway_tram_31
log_sim_rl_norway_tram_34
log_sim_rl_norway_ferry_3
log_sim_rl_norway_bus_10
log_sim_rl_norway_tram_8
log_sim_rl_norway_tram_19
log_sim_rl_norway_tram_46
log_sim_rl_norway_tram_49
log_sim_rl_norway_tram_15
log_sim_rl_norway_bus_12
log_sim_rl_norway_car_6
log_sim_rl_norway_tram_22
log_sim_rl_norway_ferry_9
log_sim_rl_norway_tram_26
log_sim_rl_norway_tram_9
log_sim_rl_norway_car_4
log_sim_rl_norway_tram_37
log_sim_rl_norway_tram_54
log_sim_rl_norway_car_10
log_sim_rl_norway_tram_20
log_sim_rl_norway_ferry_20
log_sim_rl_norway_train_19
log_sim_rl_norway_bus_6
log_sim_rl_norway_ferry_6
log_sim_rl_norway_train_9
log_sim_rl_norway_car_2
log_sim_rl_norway_tram_23
log_sim_rl_norway_bus_3
log_sim_rl_norway_metro_4
log_sim_rl_norway_tram_32
log_sim_rl_norway_train_6
log_sim_rl_norway_tram_12
log_sim_rl_norway_train_5
log_sim_rl_norway_ferry_13
log_sim_rl_norway_tram_24
log_sim_rl_norway_ferry_4
log_sim_rl_norway_bus_22
log_sim_rl_norway_tram_40
log_sim_rl_norway_tram_1
log_sim_rl_norway_bus_15
log_sim_rl_norway_tram_36
log_sim_rl_norway_train_16
log_sim_rl_norway_train_17
log_sim_rl_norway_tram_42
log_sim_rl_norway_tram_45
log_sim_rl_norway_train_15
log_sim_rl_norway_tram_30
log_sim_rl_norway_metro_3
log_sim_rl_norway_ferry_12
log_sim_rl_norway_tram_11
log_sim_rl_norway_bus_9
log_sim_rl_norway_tram_56
log_sim_rl_norway_tram_38
log_sim_rl_norway_tram_35
log_sim_rl_norway_bus_23
log_sim_rl_norway_train_12
log_sim_rl_norway_train_4
log_sim_rl_norway_train_13
log_sim_rl_norway_tram_44
log_sim_rl_norway_car_9
log_sim_rl_norway_car_11
log_sim_rl_norway_metro_6
log_sim_rl_norway_metro_8
log_sim_rl_norway_tram_3
log_sim_rl_norway_tram_13
log_sim_rl_norway_train_20
log_sim_rl_norway_tram_52
log_sim_rl_norway_tram_16
log_sim_rl_norway_metro_2
log_sim_rl_norway_ferry_15
log_sim_rl_norway_car_7
/home/osboxes/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/osboxes/.local/lib/python2.7/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

**Comment by hongzimao** [comment]
I think this similar issue should help https://github.com/hongzimao/pensieve/issues/2
