### ISSUE TITLE
/pensieve/sim/rl_test.py Randomness in picking ACTION

### ISSUE THREAD

**Issue by quito418** [hongzimao/pensieve#27]
Dear Hongzimao,

Hello, I succeeded working out with reproducing, training testing. But while training I found out that the fluctuation in test results is large (I put real world data in /sim/cooked_test_traces and kept looking at /sim/results/log_test). 
And while looking in to the code, there are some part I don't clearly understand. 

 `action_prob= actor.predict(np.reshape(state, (1, S_INFO, S_LEN)))
            action_cumsum = np.cumsum(action_prob)
            bit_rate = (action_cumsum > np.random.randint(1, RAND_RANGE) / float(RAND_RANGE)).argmax()
            # Note: we need to discretize the probability into 1/RAND_RANGE steps,
            # because there is an intrinsic discrepancy in passing single state and batch states`

In this part, which is part of rl_test.py and multi_agent.py,  as I understood the code gives probability of selecting actions with small probability. But why don't we just pick the action with the best probability.

Can you give a little help on this part.

By the way I had so much fun working with your paper.  

Thank you

**Comment by hongzimao** [comment]
Thanks for your comments.

During training time, you need to *sample* from the probability distribution. Please refer the math to section 4.2 and reference 30 for more details.

During test time, you might visit weird state space (unlikely with well-trained model though) if you keep picking best probability. For this problem, I think picking best probability should be fine. Can you actually try it and let us know the performance? Thanks.

**Comment by quito418** [comment]
I tested after getting rid of randomness in rl_test.py 

I put bit_rate=action_prob.argmax() instead of bit_rate=(action_cumsum > np.random.randint(1, RAND_RANGE) / float(RAND_RANGE)).argmax()

The validation test performance went up overall. It still fluctuated a lot, but much steady than before.

Thank you!
