### ISSUE TITLE
Question about the CNN structure

### ISSUE THREAD

**Issue by liuxs0** [hongzimao/pensieve#29]
Hi hongzi,

I have a question about the CNN structure used in the Pensieve system.

Based on my understanding, CNN layers are usually used to detect features or patterns from the data, since the convolution kernels can be seemed as filters. For example, when the past 8 chunk throughputs are feeded to an 1D-CNN, if we want to detect the change pattern of the throughput history, then the input shape should be in [?, 8, 1] (in tensorflow). And if there are 128 filters with size 4, the kernel shape will be [4, 1, 128], then we will get the output in shape [?, 8, 128].

However in the code, the input shape is [?, 1, 8], which means that the 8 history records are treated as channels, not samples in a single channel. So the filter shape is [4, 8, 128], each of the filters has 8 channels and each channel has 4 coefficients. However for each channel, since there is only 1 input sample, only 1 coefficient is actually used and other 3 ones are multiplied by padded "zeros". I am quite confused with this structure. Why the network is designed like this? Please correct me if I am wrong...Thanks!

**Comment by hongzimao** [comment]
If I remember, we used tflearn as opposed to the tensorflow built-in NN library. By design, you are right, the convolution should be applied along the time dimension. Feel free to poke around the code and see if any change makes any improvement. Please keep us updated---we are keen to know your new discovery!

**Comment by liuxs0** [comment]
Thanks for your reply, Hongzi! I tried to use the convolution applied along the time dimension, however the results are not better than using the original code.
