### ISSUE TITLE
Ensuring Latency

### ISSUE THREAD

**Issue by a-jumani** [hongzimao/pensieve#31]
Dear Hongzi Mao,

While looking at the network log using Chrome, I noticed the following:

i. Video playback client was contacting the video server using the server's IP. This means, using run_exp/run_traces.py will allow packets to go from inside the Mahimahi shell to outside and back. This will ensure the 80 ms latency that was set.

ii. Video playback client (i.e. dash.all.min.js) was contacting the ABR server using "localhost:8333". But contacting localhost bypasses Mahimahi's emulation. Hence, the delay will only be due to computation. I tested this by pinging an Apache 2 server running on my own PC:
     a. sudo sysctl net.ipv4.ip_forward=1
     b. mm-delay 2000
     c. ping -c 5 -n localhost
     d. ping -c 5 -n 10.0.2.15

Ping on localhost took avg RTT of a few ms while that from 10.0.2.15 (my VM's IP address) took 4s plus a few ms.

Table 4 of the paper suggests a range of latencies was tested. Was that achieved by using a different version of dash.all.min.js than that in this repository?

**Comment by hongzimao** [comment]
Your observation is correct -- the delay is imposed on getting the video chunk from the video server, and the ABR sever is running "_locally_" with the video client with no explicit network delay.

We performed the table 4 experiments by adding a sleep instruction in ABR server, as a quick way to simulate constant network delay.

**Comment by a-jumani** [comment]
That clears up my confusion. Thanks a lot.
