### ISSUE TITLE
Difference between CHUNK_TIL_VIDEO_END_CAP and TOTAL_VIDEO_CHUNK

### ISSUE THREAD

**Issue by chaos5958** [hongzimao/pensieve#32]
Dear Hongzi,

There are two variables (CHUNK_TIL_VIDEO_END_CAP and TOTAL_VIDEO_CHUNK) in pensieve which have same value (48). (for example, in 'test/mpc.py')
Could you explain what is the difference between these variables? 
Since I use a different video, total number of chunks also gets different.
I actually modified these two variables to total number of chunks of my video.

Thank you.
Hyunho

**Comment by hongzimao** [comment]
During development, the first parameter was for the learning agent and the second parameter was for the environment. They should be the same value. And yes, when you change it to a different video, you need to change these two variables to total number of chunks in your video. Hope this helps.
