### ISSUE TITLE
About cooked data

### ISSUE THREAD

**Issue by dogmimi** [hongzimao/pensieve#35]
Hi, 

  I'm trying to use the raw fcc data to generate the cooked data, but I didn't know how to do that. Can you provide some sample code or give a hint about how to generate? It seems that you use unit_id + target(URL) as a key to separate the traces. But in the raw data, for each unit_id + target, the interval between each log is about 2 hours. Can you tell us how to generate the cooked trace(as you provided) that interval is 5 seconds.

Thanks

**Comment by hongzimao** [comment]
We prepared the trace following the MPC paper (section 7.1.1, FCC). "For experiments we randomly pick 1000 of the _concatenated_ traces whose average throughput is between 0 to 3Mbps ..." 


Our script for processing the trace can be found at https://github.com/hongzimao/pensieve/tree/master/traces/fcc

**Comment by dogmimi** [comment]
Thanks for fast reply! I just checked the MPC paper and the fcc raw data, but it still confused me.
for example(I only cut first 3 fields), just check cnn's part
373,**2015-06-01 01:28:12**,**http://edition.cnn.com**
373,2015-06-01 01:28:17,http://www.youtube.com
373,2015-06-01 01:28:22,http://www.msn.com
373,2015-06-01 01:28:29,http://www.amazon.com
373,2015-06-01 01:28:34,http://www.ebay.com
373,2015-06-01 01:28:37,http://www.wikipedia.org
373,2015-06-01 01:28:42,http://www.google.com/mobile/
373,2015-06-01 01:28:46,http://www.facebook.com
373,2015-06-01 01:28:54,http://www.yahoo.com
373,**2015-06-01 03:26:24**,**http://edition.cnn.com**

In this case, combine 377 and cnn as key to make an individual trace and each will consume 5 seconds, so the cooked trace will be something like:
0 1.5
5.0 1.45 ...

But my question is that their actual time gap is about 2 hours, how can you interpret them as 5 seconds and perceive them as continuous change? Will that affect the training process?

Thanks!

**Comment by hongzimao** [comment]
Which FCC trace was this? I remember there were traces such as video_stream, file_download. I think we picked the one that doesn't have separation as large as 2 hours. In any case, this puzzled us at the time too. If I'm not mistaken, MPC paper suggests direct concatenation of the trace and ignore the gap.

**Comment by dogmimi** [comment]
It's from the curr_webget_2016_05.csv. Is this the file you produced the cooked traces? And you're right, MPC paper mentioned that they just concatenate those traces directly as you said. What I don't understand is why is this method eligible, or it just doesn't influence the prediction.

Thanks!

**Comment by hongzimao** [comment]
The end-to-end RL approach doesn't give an explicit "prediction". The goal is not predicting the future bandwidth, but rather capture the uncertainty of the network and incorporate that in the control. That being said, this strange way of concatenation introduces some artificial variance which might make the control policy more cautious. This is some hypothesis without rigorous analysis though. I think it will be very interesting to some experiments along this line. Let us know what you think?

**Comment by dogmimi** [comment]
Totally agreed, it should be a good research topic! Thanks for the comments, but right now I don't have specific idea how to enhance the process.
