### ISSUE TITLE
Trace iteration in run_exp

### ISSUE THREAD

**Issue by hammadmazhar1** [hongzimao/pensieve#37]
I'm trying to run Pensieve's experimental setup in 'run_exp'. I have installed all dependencies using setup.py and put some traces in 'cooked_traces'. When I run the python script 'run_all_traces.py' for the experiments, I only see one trace being tested. I verified that the experiment fetches video chunks for the trace, and generates results for the specific trace. But it does not move on to other traces.

I looked into 'chrome_retry_log' to see if there were any reports. The only thing I see there is in the form:

'BB_trace5.txt'
'Timeout'

'RL_trace5.txt
'Timeout'

Looking into the code, I can see that there is a handler for a SIGALARM signal which creates an Exception with the 'Timeout' text.

Any help in making it iterate through traces properly is appreciated.

**Comment by hongzimao** [comment]
You said one trace was loaded and video chunks were all fetched for that session. Did all the ABR schemes have the logs? Or only one scheme finish the video? I think the timeout means the video is still not done after a (very) long period of time. We added the timeout to catch corner case where the connection to ABR server is somehow, but I'm not sure if this is the cause of your problem. Hope this helps!

**Comment by hammadmazhar1** [comment]
All the ABR schemes had the logs. I think I'll write my own iterator script to avoid that particular timeout issue, or comment it out for the time being. I'll update if I see that corner case pop up.
