### ISSUE TITLE
How did you generate dash.all.min.js in video_server?

### ISSUE THREAD

**Issue by hudson-ayers** [hongzimao/pensieve#41]
I used `grunt dist` in the dash.js folder to generate a new dash.all.min.js, and found that the resulting dash.all.min.js differed from that contained in the video_server folder. I am attempting to run Pensieve over some video files which require slight changes to the dash.js code, but I cannot "recompile" the dash.js code in video_server because I cannot find what dash.js code was used to to generate the file actually used in the example testing.

Thanks in advance for any advice!

**Comment by hongzimao** [comment]
The instruction for running real experiments (over mahimahi) is in https://github.com/hongzimao/pensieve/blob/master/run_exp/README.md. We modified `dash.js/src/streaming/controllers/AbrController.js` for our ABR algorithms. I think we did the compilation in the usual way.
