### ISSUE TITLE
Version of dash.js used

### ISSUE THREAD

**Issue by hammadmazhar1** [hongzimao/pensieve#42]
Hi,
Could you indicate the exact version of dash.js you used for this work. The paper mentions v2.4, is that the exact version used. I need to add some code to limit forward buffer size, which as implemented as a feature in later versions of dash.js.

**Comment by hongzimao** [comment]
I think that should be the version. It might be a modified version of dash.js since we built the project on top of existing code. The source code has `dash.js` related code in the folder.
