### ISSUE TITLE
If two video stream will effect each other in mahimahi env?

### ISSUE THREAD

**Issue by mashoujiang** [hongzimao/pensieve#45]
Hi Hongzi,

Thanks for your great work, I build up the real_exp successfully! 
But I have one concern as title, if I run two video stream in one mahimahi env, do they effect each other? I mean the trace in mahimahi will limit the throughput, if the two video streams share the same link bandwidth, I think maybe they will effect each other, am I right?

**Comment by NcuBluecoffee** [comment]
Hi mashoujiang，
I want to build up the real_exp as you, can you give me your email, and  gvie me some instruction? Thank you very much.

**Comment by mashoujiang** [comment]
hi @NcuBluecoffee ,
My email shoujiangma#163.com, but I rarely check my personal email. I think you can post your questions here, and lots of people will help you, if they have the same questions, it will help them, too. Besides, I think you can get whatever you want from Hongzi's instruction. Good luck!

**Comment by hongzimao** [comment]
Dash video player runs as an application in mahimahi network emulator. If you run two streams across the same mahimahi shell, they will share the network. It is up to the underlining network you emulate to share the bandwidth for two programs (like in a real network). Hope this helps!
