### ISSUE TITLE
Problems with Reproducing Figure 11

### ISSUE THREAD

**Issue by ptcrews** [hongzimao/pensieve#47]
Hi,
As part of a class at Stanford, my team and I are attempting to reproduce several figures in the Pensieve paper, but we have run into some issues with Figure 11. In particular, we were wondering if you had network information for the last link. In our tests, the QoE values we computed were significantly higher than the paper, even when evaluating a link from San Francisco to China. We wanted to know if you had any bandwidth and latency numbers for the networks tested in Figure 11, or if you could at least qualitatively describe the networks that your host and client were connected to.

Thanks,
Paul Crews

**Comment by hongzimao** [comment]
Hi Paul,

Sorry for the long delay. We may have lost the traces that we used. If I remember, it was a pretty congested network link with high variance. The fact that QoE values you received is significantly higher might mean there are no much hard ABR decisions to make (e.g., one can simply choose highest bitrate all the time). On the links with large bandwidth, Pensieve might not show large performance improvements. We particularly trained and tested Pensieve in those challenging scenarios to see what it can learn (similar to how prior work evaluates the ABR schemes).
