### ISSUE TITLE
Playback restarted when all fragments downloaded

### ISSUE THREAD

**Issue by pablogil16** [hongzimao/pensieve#5]
Hi all,

I have been testing the code in dash_client, and in turn the generated dash.all.js file, and I realised the playback is restarted when all the fragments have been downloaded, without playing the whole video. 

Why does the player behave this way? And would it be possible to modify the provided code in such a way the complete video is played and the playback finished after that?

Thanks!

P.S.: I just checked the provided, compiled dash.all.min.js code and it presents the same behaviour

**Comment by hongzimao** [comment]
Good observation! The reason we did that is mainly for faster evaluation. Notice that once the chunk is downloaded, the QoE score can already be determined, without spending time actually "watching" the entire video (in virtual display).

**Comment by pablogil16** [comment]
I didn't realise, but it is an interesting way to keep evaluation time down. Thank you!
