### ISSUE TITLE
Range of bit rates supported by pensieve

### ISSUE THREAD

**Issue by jlabhishek** [hongzimao/pensieve#54]
The paper (Sec 4.3) talks about 13 levels of bitrate(maybe I misunderstood) , and the training code use 8 actions, is the pre-trained model training for for range only(till 8000kbps) or it supports higher rates also.
Also how can we include a bigger range if it does not ?

Thanks you

**Comment by hongzimao** [comment]
Section 4.3 is about using one single model for multiple types of videos. The code for this is in `multi_video_sim/`
