### ISSUE TITLE
Changing ENTROPY WEIGHT with training

### ISSUE THREAD

**Issue by Zahaib** [hongzimao/pensieve#6]
Hi,

We are having a little bit of trouble integrating the suggestion for adapting the `ENTROPY_WEIGHT` parameter as the training proceeds. Is it possible to describe, a little descriptively, what implementation changes are needed for it.

Specifically, once the training starts, how should we pass `ENTROPY_WEIGHT` as a parameter to the `a3c.py` module? As of now it seems that  `ENTROPY_WEIGHT` is only used once when the `ActorNetwork` is initialized.

Further, as provided, the value of `ENTROPY_WEIGHT` in `a3c.py` is set to  `0.5`. Is this a static value which results in a reasonable model?

Thanks.

**Comment by hongzimao** [comment]
So `ENTROPY_WEIGHT` needs to be decreased in another run by explicitly setting the parameter (and loading the model in previous run, if there is any).

You can change the implementation fairly easily to enable automatic adaptation of this entropy weight. We set it as a static variable just for users to notice the impact of this term. 

As we mentioned in `README.md` in `/sim`, `ENTROPY_WEIGHT=0.5` is only an initial value. In order to reach a good performance, you need to reduce it as the training goes.

Hope this helps.

**Comment by Zahaib** [comment]
I see, so is the following an appropriate plan:

Start the training with `ENTROPY_WEIGHT  = 5` and let it run till 20,000 iteration. Afterwards change it to 4 and let it run for another 20,000 iterations.

Repeat the process untill, say 100000 iterations, by which `ENTROPY_WEIGHT  = 0.01`. 

I suppose the way the training works, if there is a model present, it will read it and then process it further? So question is if I stop the training at 20,000 iterations to update the `ENTROPY_WEIGHT` can I just read from the checkpoint and resume from 20k iteration onwards.

**Comment by hongzimao** [comment]
Use `NN_MODEL`, as suggested in `README.md` of `/sim`.

**Comment by Zahaib** [comment]
Yeah for some of our experiments we have different weights than the ones used in the linear QoE model, provided as the `NN_MODEL`.

We are evaluating for a user who is more concerned about rebuffering so we need to update the `REBUF_PENALTY = 8.6`

**Comment by hongzimao** [comment]
Yep, that should be the right place to adapt for your own situation. Make sure the training and testing are consistent about this weight.

**Comment by Zahaib** [comment]
Definitely, will ensure that.

Any thoughts on my previous questions:

A possible strategy for adapting `ENTROPY_WEIGHT`
0-19999 iteration `ENTROPY_WEIGHT = 5`
20000-39999 iteration `ENTROPY_WEIGHT = 4`
40000-59999 iteration `ENTROPY_WEIGHT = 3`
40000-59999 iteration `ENTROPY_WEIGHT = 2`
60000-79999 iteration `ENTROPY_WEIGHT = 1`
80000-89999 iteration `ENTROPY_WEIGHT = 0.5`
90000-100000 iteration `ENTROPY_WEIGHT = 0.01`

Second, can I stop the training, and just start from the checkpoint and resume onwards?

**Comment by hongzimao** [comment]
That sounds reasonable. I think a few others have tried similar things and got it worked. Hope the same for you :)

**Comment by Zahaib** [comment]
Got it, thanks for the help here.
