### ISSUE TITLE
Results for run_exp/

### ISSUE THREAD

**Issue by zhou000** [hongzimao/pensieve#63]
When you get the results which only 14 lines of records in each result. You may get the figures as follows:

![figure_on_fcc_2](https://user-images.githubusercontent.com/25151131/49708183-8486ea00-fc69-11e8-891a-075d3b652164.png)
![figure_on_norway_2](https://user-images.githubusercontent.com/25151131/49708187-8c468e80-fc69-11e8-976f-2e28dc52fd48.png).

However, it is not the full results. If you use the latest-stable google chrome, you can get the full results when you click the 'videoPlayer' button in the 'url' HTML page. Moreover, you can add the 'click button' sentences in run_exp/run_video.py, then it will load the full video automatically and you can get the full results.

**Comment by hongzimao** [comment]
Can you also show your full results?

**Comment by zhou000** [comment]
The full results are as follows:
![figure_fcc_2](https://user-images.githubusercontent.com/25151131/49708844-51922580-fc6c-11e8-9d18-d440617eaa41.png)
![figure_norway_2](https://user-images.githubusercontent.com/25151131/49708846-548d1600-fc6c-11e8-9c4a-3dc5fc1bd7a1.png).

**Comment by lsaejn** [comment]
hi, my friend! are these results right? i'm really confused..... 
![image](https://user-images.githubusercontent.com/32359144/50955668-b7383280-14f4-11e9-90c2-3b16cd5c35cd.png)

the length are not same, and  'BB' didn't swtich bitrate 
![image](https://user-images.githubusercontent.com/32359144/50955782-f36b9300-14f4-11e9-86ff-eab068040e04.png)

**Comment by hongzimao** [comment]
@zhou000 just circle back to this issue---it seems to be a chrome issue. In our refactored codebase (along with many other system environments), we use the following method to automatically start video playing: https://github.com/park-project/park/blob/master/park/envs/abr/run_video.py#L63

Thanks for pointing out the issue last time! The results above look good.
