### ISSUE TITLE
about the result of run_all_traces.py

### ISSUE THREAD

**Issue by lsaejn** [hongzimao/pensieve#64]
after run run_all_traces.py, i get log files as follow(there are many trace file in ./cooked_traces/,but i can get logfile of only one trace file ):
-----------------------------------------------------------------------------------------
log_BB_test_fcc_trace_216810_http---www.facebook.com_360
log_BOLA_test_fcc_trace_216810_http---www.facebook.com_360
log_fastMPC_test_fcc_trace_216810_http---www.facebook.com_360
log_FESTIVE_test_fcc_trace_216810_http---www.facebook.com_360
log_FIXED_test_fcc_trace_216810_http---www.facebook.com_360
log_RB_test_fcc_trace_216810_http---www.facebook.com_360
log_RL_test_fcc_trace_216810_http---www.facebook.com_360
log_robustMPC_test_fcc_trace_216810_http---www.facebook.com_360
-----------------------------------------------------------------------------------------

and  they all only has 14 lines,  plot_results.py fail to plot, because 14<VIDEO_LEN
-----------------------------------------------------------------------------------------
if l not in time_all[scheme] or len(time_all[scheme][l]) < VIDEO_LEN:
	schemes_check = False
	break
-----------------------------------------------------------------------------------------

How can i  manage this? Thank you !!

**Comment by hongzimao** [comment]
14 lines mean 14 ABR actions were made. One potential problem is the video is not playing and the buffer stops to populate when it reaches a limit (like 60 seconds). Can you check if the real video is actually playing?

**Comment by lsaejn** [comment]
Thank you! I fix it (not sure) by add a sentence to click 'VideoPlay' button. But i'm still confused, does pensieve  run on BaseHTTPServer and the other algorithms run on apache server?
