### ISSUE TITLE
issues related to running mpc.py in test

### ISSUE THREAD

**Issue by bekiroguzhan** [hongzimao/pensieve#72]
I am able to run rl_no_training.py and bb.py to retrieve the test result with the pre-trained model but when I run python mpc.py I get the below error.  Could you please help me to resolve the matter?

ubuntu@****:~/pensieve/test$ python mpc.py
Traceback (most recent call last):
  File "mpc.py", line 271, in <module>
    main()
  File "mpc.py", line 91, in main
    net_env.get_video_chunk(bit_rate)
ValueError: too many values to unpack

**Comment by Suliucuc** [comment]
I think maybe the actual return values don't match the return value in function definition,you can chexk it.The right code should be  
delay, sleep_time, buffer_size, rebuf, \
       video_chunk_size, next_video_chunk_sizes, \
        end_of_video, video_chunk_remain = \
            net_env.get_video_chunk(bit_rate)
