### ISSUE TITLE
Fail to download the cooked_traces or cooked_test_traces

### ISSUE THREAD

**Issue by xiaomingloveLF** [hongzimao/pensieve#75]
Hi Mr.Mao,
    Sorry to bother you and your solution is great.
    I am trying to learn your project, but according to your guide, I can't access and download the cooked_traces or cooked_test_traces data from the URL: https://www.dropbox.com/sh/ss0zs1lc4cklu3u/AAB-8WC3cHD4PTtYT0E4M19Ja?dl=0.
    Can you share the new one which can access into and download the data?

Best Regards

**Comment by hongzimao** [comment]
I'm pretty sure it's still accessible---please try again?

**Comment by weiyuxingchen** [comment]
I have the same problem. I can't access and download the cooked_traces or cooked_test_traces data from the URL: https://www.dropbox.com/sh/ss0zs1lc4cklu3u/AAB-8WC3cHD4PTtYT0E4M19Ja?dl=0.

**Comment by hongzimao** [comment]
Weird. I can still access it. Is dropbox somehow blocked in your ISP (can you try other dropbox urls)? If it still doesn't work, send me an email and I will send you the zip file.
