### ISSUE TITLE
Range of bandwidth the linear model is trained on?

### ISSUE THREAD

**Issue by Zahaib** [hongzimao/pensieve#8]
Hey,

I noticed that the bandwidth traces you guys provided. The average BW across those traces is mostly less than 3000Kbps. Is this the same range of bandwidth the linear QoE model is trained for or has it also been trained for higher bandwidths like between 7000Kbps-9000Kbps?

I ask this because I may need to evaluate Pensieve on slightly higher bandwidths and would like to make sure if I need to retrain for it or not.

Thanks.

**Comment by hongzimao** [comment]
The traces we used is mostly less than 4.5Mbps. The reason (originally argued by MPC paper, which we follow) is to create challenging environment for bitrate decisions (ABR can be straightforward for too large or too small bandwidth).

Yes, I think you need to retrain Pensieve in your environment for fair comparison.

**Comment by Zahaib** [comment]
Makes sense, thanks.

**Comment by yun-nam** [comment]
Hi Hongzi, 
Thanks for your great work.
I am wondering whether the traces you provided is subset of your traces or full set of traces you used in the paper for training and testing..

Thanks

Yun

**Comment by hongzimao** [comment]
Should be full. We also provided the links to raw traces and the way we processed them in `traces/`.
