### ISSUE TITLE
cooked_traces format

### ISSUE THREAD

**Issue by r02b** [hongzimao/pensieve#86]
Hey Hongzi,

The readmes state that the format is:
[ [time_stamp (sec), throughput (Mbit/sec)]](url)
however, this seems to cause errors, and the cooked_traces you provided through dropbox seems to be of the format:
`[time_stamp (sec)\t throughput (Mbit/sec)]`

Am I doing something wrong?

Thanks!

**Comment by hongzimao** [comment]
What's the error you get from reading the file? Python's line split function should do the right thing parsing `\t` or `,`.

**Comment by r02b** [comment]
Sorry for the late reply, took me a while to remember what this was about :) Fix was rather simple as you mentioned. Thanks HongZi!
