### ISSUE TITLE
How to generate the Fig 7,10 and 11.

### ISSUE THREAD

**Issue by mandannaresh8686bits** [hongzimao/pensieve#91]
Could you explain how to generate Fig 7,10 and 11.

**Comment by hongzimao** [comment]
The data was generated from the code in this repo and is described in section 5 of the paper. I plotted the figures using excel at that time. Let me know if this answers your question? If not, could you be more specific for how we can help?

**Comment by mandannaresh8686bits** [comment]
Thanks you for early response. But what parameters can I take to plot the bar chart of Fig 7,10,11 by using Excel. Which code I want to run.

**Comment by hongzimao** [comment]
I didn't write code when drawing with Excel. You just load the data and plot it. You can adjust the parameter for the bar width, color, pattern, etc. with the Excel UI.

**Comment by mandannaresh8686bits** [comment]
Thank you for early response.
