### ISSUE TITLE
How to simulate the BW fluctuation?

### ISSUE THREAD

**Issue by RoyE3BBB** [hongzimao/pensieve#94]
Hi!How could I simulate the network enviroment like Figure 3 and trace the true bandwidth?

**Comment by hongzimao** [comment]
The trace files are included in https://github.com/hongzimao/pensieve/blob/master/traces/README.md. You can load the trace for the simulator in https://github.com/hongzimao/pensieve/tree/master/sim. IIRC, figure 3a is a synthetic trace to showcase and motivate the problem with a fixed ABR scheme (i.e., too conservative in sawtooth bandwidth trace). You can generate similar trace and load it to the simulator.
